# Default values for nfs-client.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

nfs.server: nuc1.galaxy
nfs-path: /exports/ocp1.galaxy

nameOverride: "nfs-storage"
