# Default values for prometheus-external-service.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
# fullnameOverride: external-infra-monitor-
nameOverride: ""
fullnameOverride: ""
service:
  infra_metric_port: 9100
monitor:
  interval: 30s  
external_infra_list: 
  - nuc1_192.168.2.10
  - nuc2_192.168.2.20
  - w520_192.168.2.30
  - w541_192.168.2.40
  - dns-1_192.168.2.15
  - lb1-1_192.168.2.16
  - bastion-1_192.168.2.17
  - elk-1_192.168.2.18
  - lb2-1_192.168.2.19
  - rhsso-1_192.168.2.25
  - squid-1_192.168.2.28
  - jbeap1-w520_192.168.2.33
  - jbpeap2-w520_192.168.2.35
  - lb-httpd1-w541_192.168.2.45
  - lb-httpd2-w541_192.168.2.46
  - lb-httpd3-w541_192.168.2.47
  - lb-httpd4-w541_192.168.2.48
external_app_list:
  - todo-app_192.168.2.10_8080
  - squid_192.168.2.28_9101
