apiVersion: integreatly.org/v1alpha1
kind: GrafanaDataSource
metadata:
  name: prometheus-grafanadatasource
  namespace: {{ .Values.namespace }}
spec:
  datasources:
  - access: proxy
    editable: true
    isDefault: true
    jsonData:
      httpHeaderName1: Authorization
      timeInterval: 5s
      tlsSkipVerify: true
    name: Prometheus
    secureJsonData:
      # httpHeaderValue1: Bearer {{ .Values.token }}
      httpHeaderValue1: Bearer eyJhbGciOiJSUzI1NiIsImtpZCI6Ik0yUnEtdUdodGF2V05oWnlZUFRldmVGNVJpZFBvaGhDeDRBR2paYWhFMHMifQ.eyJpc3MiOiJrdWJlcm5ldGVzL3NlcnZpY2VhY2NvdW50Iiwia3ViZXJuZXRlcy5pby9zZXJ2aWNlYWNjb3VudC9uYW1lc3BhY2UiOiJteS1ncmFmYW5hIiwia3ViZXJuZXRlcy5pby9zZXJ2aWNlYWNjb3VudC9zZWNyZXQubmFtZSI6ImdyYWZhbmEtc2VydmljZWFjY291bnQtdG9rZW4tcjluNGgiLCJrdWJlcm5ldGVzLmlvL3NlcnZpY2VhY2NvdW50L3NlcnZpY2UtYWNjb3VudC5uYW1lIjoiZ3JhZmFuYS1zZXJ2aWNlYWNjb3VudCIsImt1YmVybmV0ZXMuaW8vc2VydmljZWFjY291bnQvc2VydmljZS1hY2NvdW50LnVpZCI6IjZkNzUyYzY3LWY3ZGEtNDEwNy1iNWZmLWM5NjJjMDhkMzFkZiIsInN1YiI6InN5c3RlbTpzZXJ2aWNlYWNjb3VudDpteS1ncmFmYW5hOmdyYWZhbmEtc2VydmljZWFjY291bnQifQ.UzS1k_7-2N2QmC0JnyNXINIKFB0I3C-5Hcsy_CxNU-mCNJsEmN_PsYFxXbs6IUN9pIFdiSytUPX7hmy-cZPwH4DhNgdTc038vS6TQxA8xdZyf0zxKULIDq3bOz0JSfME9SIyCI-0ozdct8-xO9kcVQzw2bAsfCsCr3Y1iniK6IwAK0ouwS_lLIvDCkDfY3IceIzDDU0PsKexVRiRw3YiJ4GVrV8Ih6B2Lm1fXwvpY7oZvqG68Ryq8685IwXFLjLxOTc2zAb7M-EGYMpe-v3Wbv8SPuLqYKGAcMoUVPqTwGk2vo3ghCtuc0Tyi38Bh8ize51PtR7oB5rYAK3H9Gu0hQ
    type: prometheus
    url: https://thanos-querier.openshift-monitoring.svc.cluster.local:9091
  name: prometheus-grafanadatasource.yaml

