apiVersion: integreatly.org/v1alpha1
kind: GrafanaDataSource
metadata:
  name: prometheus-grafanadatasource
  namespace: {{ .Values.namespace }}
spec:
  datasources:
  - access: proxy
    editable: true
    isDefault: true
    jsonData:
      httpHeaderName1: Authorization
      timeInterval: 5s
      tlsSkipVerify: true
    name: Prometheus
    secureJsonData:
      httpHeaderValue1: Bearer {{ .Values.token }}
    type: prometheus
    url: https://thanos-querier.openshift-monitoring.svc.cluster.local:9091
  name: prometheus-grafanadatasource.yaml

