{{- range .Values.external_infra_list }}
{{- $parts := split "_" . }}
apiVersion: v1
kind: Service
metadata:
  name: ext-metric-{{ $parts._0}}
  labels:
    external-infra-monitor: "true"
  namespace: external-service
spec:
  ports:
  - name: web
    port: {{ $.Values.service.port }}
    protocol: TCP
    targetPort: 8080
  selector: {}
  sessionAffinity: None
  type: ClusterIP
---
{{- end }}
