apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  creationTimestamp: "2021-03-19T15:33:36Z"
  managedFields:
  - apiVersion: rbac.authorization.k8s.io/v1
    fieldsType: FieldsV1
    fieldsV1:
      f:roleRef:
        f:apiGroup: {}
        f:kind: {}
        f:name: {}
      f:subjects: {}
    manager: Mozilla
    operation: Update
    time: "2021-03-19T15:33:36Z"
  name: AppMonitoring
  namespace: sandbox
  resourceVersion: "466479"
  selfLink: /apis/rbac.authorization.k8s.io/v1/namespaces/sandbox/rolebindings/AppMonitoring
  uid: b6dc9515-47f0-49c0-acea-4847f68b1f41
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: monitoring-edit
subjects:
- apiGroup: rbac.authorization.k8s.io
  kind: Group
  name: developer
